### ISSUE TITLE
Suggestions for other networked notebooks

### ISSUE THREAD

**Issue by raghudotcc** [prathyvsh/networked-notebooks#1]
Below are some Zettlekesten-based (Roam Research like) apps that are up and coming, some of them are under heavy development, while some seem to have been abandoned:

1. [Amplenote](https://www.amplenote.com/)
> Started as a run of the mill note-taking app, but seems to be implementing Roam-like features. Already has support for Backlinks and context. 
> ![](https://images.amplenote.com/ca68f6b2-8fb6-11ea-9b04-caf4dc8d4992/6d54960f-2cea-4dd5-b5db-e8e410705d07.png)

2. [Orgroam](https://org-roam.readthedocs.io/en/master/)
> ![](https://org-roam.readthedocs.io/en/master/images/org-roam-intro.png)
> Out of the bunch, this is probably the most promising of them all. Has implemented most of the core functionality of Roam like being able to see connected graphs, backlinks, title autocompletion, networked search, etc and is in heavy development. Also works with orgmode if that’s your thing.

3. Dockuwiki([Dokuroam](https://github.com/andjar/dokuroam/blob/master/README.md))
> ![image](https://user-images.githubusercontent.com/24671386/81791111-e9f89d80-9523-11ea-89ff-63b658945189.png)
> DokuWiki based implementation of Roam Research. Roam Research has rapidly gained popularity by opening up to new workflows. Has some but not all of Roam’s features, but is in active development.

4. [Zettlr](https://www.zettlr.com/)
> ![](https://docs.zettlr.com/en/img/zettlr_ide.png)
> Basically a markdown editor like Typora, but has a [zettlekesten mode](https://docs.zettlr.com/en/guides/guide-zettelkasten/) for handling the connection. Also the design is surprisingly good for an OSS.

5. [Free-roam](https://github.com/cofinley/free-roam)
> Connor Finley started development on this in an attempt to open source core features of roam, but seems to have abandoned after having found TiddlyWiki

6. [Athens](https://github.com/athensresearch/athens)
> ![image](https://user-images.githubusercontent.com/24671386/81790871-a00fb780-9523-11ea-98e6-dec05adc5af8.png)
> An open source implementation of Roam. (Under heavy development)
> Has very basic UI

7.  [Lotu](https://twitter.com/hanbzu/status/1258352174242897920?s=21)
> ![](https://pbs.twimg.com/media/EXaQWrsWsAApfzK?format=jpg&name=large)
>  Not a product per-se, but from the discussion, the prototype seems interesting. It is an attempt to create a densely connected Digital Garden. (Don’t know what a digital garden is, but has become a popular term for describing websites that incorporate multiple facets of a person’s digital space like notes, blog etc into a single thing and allows visitors to stroll through them seamlessly like a garden with densely connected graph like structure). 
> - [Ward Cunnigham's Federated Wiki](http://fed.wiki.org/view/welcome-visitors)
>> Seems like Ward is the inventer of this Andy matuschak like layout. Can't say, but at least from the look of it, 2011 precedes 2018. Maybe both of them had the same source of inspiration.
>
> Some examples of digital garden: 
> - [Gordon Brander’s Personal Website](http://gordonbrander.com/pattern/)
> - [Andy Matuschak’s Notes](https://notes.andymatuschak.com)
> - [Azlen Elza’s Notes](https://notes.azlen.me/g3tibyfv/): [Code](https://github.com/azlen/azlen.me/tree/master/notes)
> - [Joel Hook’s Blog](https://joelhooks.com/)
> - [Tom Critchlow’s Website](https://tomcritchlow.com/)

8. [Knovigator](https://knovigator.com)
> An online application with support for branching and threading like Twitter. Optimized for curation and conversation. Under development

9. [Obsidian](https://obsidian.md/)
> ![](https://i.imgur.com/LSZlIT9.png)
> Similar to Zettlr, a markdown editor. But has support for zettlekesten mode. Has backlinks and Graph support.

10. [Remnote](https://www.remnote.io)
> ![image](https://user-images.githubusercontent.com/24671386/81788119-a9972080-951f-11ea-8fb1-d4279ed49a91.png)
> A comprehensive tool for knowledge management. Includes Spaced Repetition, Graphs, Backlinks etc.

11. [ikiWiki](https://ikiwiki.info/)
> Basic wiki with backlinks.

12. [nvUltra](https://nvultra.com/)
> Based on the good old notational velocity. Supports Markdown, backlinks etc. Still in Beta
> Also has a previous version called nvAlt

13. [zim](https://zim-wiki.org)
> Basic wiki with backlinks. Supports pretty much all types of [linkages](https://zim-wiki.org/manual/Help/Links.html)

**Comment by prathyvsh** [comment]
Thanks a lot for the input, I have tried to incorporate most of this into the repo. Looking through the list made me think that there needs to be more classification as many of these seem to be on various gradations of a spectrum as far as their features are concerned. Will try to come up with one once I have more familiarity with the problem space. Thanks a lot for these man!
